.gitignore, content/en/_index.html, content/en/docs/_index.md
API builder poc
Thank you for your contribution to the APIBuilderPOC-Open-Docs repo.
Updated the configuration files to replace template content with API Builder POC.
* [x ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [x ] You have signed the [Axway CLA](https://cla.axway.com/)
* [x ] You have verified the technical accuracy of your change
* [x ] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
_This section is to be filled out …
=> Configure api builder poc microsite

layouts/shortcodes/variables/apibuilder_prod_name.html
Thank you for your contribution to the Axway-Open-Docs (API Builder POC) repo.
Added a shorcode for the API Builder product name variable. 
=> added shortcode variable for the API Builder product name

build.sh, content/en/docs/Best_Practices.md, content/en/docs/_index.md
Updated the build script with Wing's code so the files will use the gitinfo when doing the build. Tested this with the Overview and Best Practices pages and see that the Last modified date is automatically updated with the commit message in the footer of the page. This now works as it did with the Axway Open Docs project.
* [x ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [x ] You have signed the [Axway CLA](https://cla.axway.com/)
* [x ] You have verified the technical accuracy of your change
* [x ] You have …
=> Update build script and tested it

content/en/docs/Getting_Started_With_API_Builder.md, package-lock.json, package.json
For security (PSG) I am testing adding HTML code that is an alert box pop up to see if Zoomin publishes it. 
=> adding an HTML alert box for testing zoomin rendering

content/en/docs/deprecations/_index.md, content/en/docs/developer_guide/connectors/mysql_connector.md, content/en/docs/developer_guide/flows/flow_nodes/codeblock_flow_node.md, content/en/docs/developer_guide/flows/flow_nodes/compose_flow_node.md, content/en/docs/developer_guide/flows/flow_nodes/dot_flow_node.md, content/en/docs/developer_guide/flows/flow_nodes/javascript_flow_node.md, content/en/docs/developer_guide/flows/flow_nodes/logger_flow_node.md, content/en/docs/developer_guide/flows/flow_triggers/cron_flow_trigger.md, content/en/docs/developer_guide/web.md, content/en/docs/how_to/deploy_an_api_builder_application_to_amplify_runtime_services.md, content/en/docs/how_to/track_usage_for_your_subscription.md, content/en/docs/security_guide/_index.md, content/en/docs/updates/2021_08_27_update_axway_api_builder_oas_flow_node_that_effects_openapi_plugins.md, content/en/docs/v3_to_v4_upgrade_guide/_index.md
=> Make warning alerts look better

content/en/docs/release_notes/xalapa.md
=> Add xalapa release notes

content/en/docs/release_notes/york.md
=> RDPP-7100: Added release-note

content/en/docs/how_to/enable_prometheus_metrics.md, content/en/docs/release_notes/exeter.md
=> RDPP-7196: added prometheus plugin

content/en/docs/developer_guide/flows/flow_triggers/oas_flow_trigger.md, content/en/docs/developer_guide/project/configuration/project_configuration.md, content/en/docs/how_to/enable_prometheus_metrics.md, content/en/docs/release_notes/djibouti.md, content/en/docs/release_notes/exeter.md, content/en/docs/release_notes/flint.md
=> Flint release notes

content/en/docs/developer_guide/flows/flow_triggers/oas_flow_trigger.md, content/en/docs/release_notes/exeter.md
=> Copy edits and update common submodule to remove contribution guidelines

data/deprecations.yaml
Two links for the deprecations D047 and D048 are broken as very likely the remaining index.html is missing.
https://deploy-preview-59--api-builder-docs.netlify.app/docs/deprecations/#D047
=> Fixed a broken link in the generated deprecation page

content/en/docs/developer_guide/flows/flow_triggers/oas_flow_trigger.md
=> RDPP-7289: document JSON schema formats

content/en/docs/release_notes/haarlem.md
=> RDPP-7280: Disable endpoints generation for models.

content/en/docs/deprecations/runtime_peer.md, content/en/docs/getting_started/_index.md
=> Kabul release notes (reprise)

content/en/docs/deprecations/runtime_peer.md
=> Kabul release 2

content/en/docs/how_to/enable_prometheus_metrics.md, content/en/docs/release_notes/paris.md
=> Paris release notes

config.toml, netlify.toml
Update Hugo version and use goldmark markup version instead of blackFriday.
=> Update Hugo version and use goldmark

content/en/docs/release_notes/beckett.md
=> Beckett Release

content/en/docs/developer_guide/console/models.md, content/en/docs/developer_guide/flows/manage_flows/flow_examples/count_users.md, content/en/docs/developer_guide/flows/manage_flows/flow_examples/create_a_user.md, content/en/docs/developer_guide/flows/manage_flows/flow_examples/delete_a_user.md, content/en/docs/developer_guide/flows/manage_flows/flow_examples/delete_all_users.md, content/en/docs/developer_guide/flows/manage_flows/flow_examples/find_a_distinct_user.md, content/en/docs/developer_guide/flows/manage_flows/flow_examples/find_a_user_by_id.md, content/en/docs/developer_guide/flows/manage_flows/flow_examples/find_all_users.md, content/en/docs/developer_guide/flows/manage_flows/flow_examples/find_and_modify_users.md, content/en/docs/developer_guide/flows/manage_flows/flow_examples/query_a_user.md, content/en/docs/developer_guide/flows/manage_flows/flow_examples/update_a_user.md, content/en/docs/developer_guide/flows/manage_flows/flow_examples/upsert_a_user.md, content/en/docs/developer_guide/models/create.md, content/en/docs/getting_started/_index.md, content/en/docs/guide_openapi/openapi_tips.md, content/en/docs/how_to/authorization_access_microsoft_onedrive_using_rest_flow_node.md, content/en/docs/how_to/create_a_custom_flow_node.md, content/en/docs/nodejs_support_policy/_index.md, content/en/docs/performance_metrics/_index.md
Fixed some formatting issues with images after upgrading to the new Zoomin doc portal. 
=> Fixed formatting issues after Zoomin upgrade to new doc portal

config.toml
=> RDAPI-29447 fix code block syntax issue

content/en/docs/guide_openapi/quick_start.md
=> bookstore link

content/en/docs/developer_guide/project/configuration/project_configuration.md, content/en/docs/developer_guide/project/logging.md, content/en/docs/how_to/enable_json_service_logs.md, content/en/docs/release_notes/xiangxiang.md
=> Xiangxiang Release.

.gitignore, content/en/docs/guide_openapi/quick_start.md, content/en/docs/release_notes/_index.md, content/en/docs/release_notes/fleming.md, content/en/docs/release_notes/glaspell.md
=> Gate release notes and known issues

content/en/docs/release_notes/huxley.md
=> Huxley Release.

.gitignore, content/en/docs/release_notes/_index.md
=> Gate Release Notes dated February 2022 and later

content/en/docs/release_notes/irving.md
=> Add Irving release.

content/en/docs/release_notes/zaanstad.md
=> Add Zaanstad release.

content/en/docs/guide_openapi/writing_apidocs.md
=> Add unsupported parameter nullable.

.gitignore, content/en/docs/release_notes/lee.md
=> Lee release.
